### ISSUE TITLE
The reaction order

### ISSUE THREAD

**Issue by Mianlex** [sudarshanv01/tpd_analyse#1]
In the main.py code , Line 29. and 30:
    **## Order of the reaction
    order = 1**
The reaction order is an parameter, however, when we change the creation order to 0 or 2.  The code can not run and got struck.  Only order=1 run well.

Error Report:
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    TPDClass.get_results()
  File "/home/cat/mianle/Package/tpd_analyse/tpd_analyse/tpd.py", line 126, in get_results
    self.norm_results[exposure] = experimentalTPD(tpd_filename=f,
  File "/home/cat/mianle/Package/tpd_analyse/tpd_analyse/tools/parser_class.py", line 161, in __init__
    raise NotImplementedError
NotImplementedError

**Comment by sudarshanv01** [comment]
Yup, only implemented for 1st order
